<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Rt extends CI_Controller
{
    var $judul_page = "Rt";
    function __construct()
    {
        parent::__construct();
        $this->load->model('Rt_model');
        $this->load->library('form_validation');
        if ($this->session->userdata('level') == '') {
            redirect('login');
        }
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'rt/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'rt/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'rt/index.html';
            $config['first_url'] = base_url() . 'rt/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Rt_model->total_rows($q);
        $rt = $this->Rt_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'rt_data' => $rt,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
            'judul_page' => $this->judul_page,
            'konten' => 'rt/rt_list',
        );
        $this->load->view('v_index', $data);
    }

    public function read($id) 
    {
        $row = $this->Rt_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_rt' => $row->id_rt,
		'rt' => $row->rt,
	    );
            $this->load->view('rt/rt_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('rt'));
        }
    }

    public function create() 
    {
        $data = array(
            'judul_page' => $this->judul_page,
            'konten' => 'rt/rt_form',
            'button' => 'Create',
            'action' => site_url('rt/create_action'),
	    'id_rt' => set_value('id_rt'),
	    'rt' => set_value('rt'),
	);
        $this->load->view('v_index', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'rt' => $this->input->post('rt',TRUE),
	    );

            $this->Rt_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('rt'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Rt_model->get_by_id($id);

        if ($row) {
            $data = array(
                'judul_page' => $this->judul_page,
                'konten' => 'rt/rt_form',
                'button' => 'Update',
                'action' => site_url('rt/update_action'),
		'id_rt' => set_value('id_rt', $row->id_rt),
		'rt' => set_value('rt', $row->rt),
	    );
            $this->load->view('v_index', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('rt'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_rt', TRUE));
        } else {
            $data = array(
		'rt' => $this->input->post('rt',TRUE),
	    );

            $this->Rt_model->update($this->input->post('id_rt', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('rt'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Rt_model->get_by_id($id);

        if ($row) {
            $this->Rt_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('rt'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('rt'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('rt', 'rt', 'trim|required');

	$this->form_validation->set_rules('id_rt', 'id_rt', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Rt.php */
/* Location: ./application/controllers/Rt.php */
/* Please DO NOT modify this information : */
/* Generated by Boy Kurniawan 2022-08-03 17:37:07 */
/* https://jualkoding.com */