<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Rw extends CI_Controller
{
    var $judul_page = "Rw";
    function __construct()
    {
        parent::__construct();
        $this->load->model('Rw_model');
        $this->load->library('form_validation');
        if ($this->session->userdata('level') == '') {
            redirect('login');
        }
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'rw/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'rw/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'rw/index.html';
            $config['first_url'] = base_url() . 'rw/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Rw_model->total_rows($q);
        $rw = $this->Rw_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'rw_data' => $rw,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
            'judul_page' => $this->judul_page,
            'konten' => 'rw/rw_list',
        );
        $this->load->view('v_index', $data);
    }

    public function read($id) 
    {
        $row = $this->Rw_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_rw' => $row->id_rw,
		'rw' => $row->rw,
	    );
            $this->load->view('rw/rw_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('rw'));
        }
    }

    public function create() 
    {
        $data = array(
            'judul_page' => $this->judul_page,
            'konten' => 'rw/rw_form',
            'button' => 'Create',
            'action' => site_url('rw/create_action'),
	    'id_rw' => set_value('id_rw'),
	    'rw' => set_value('rw'),
	);
        $this->load->view('v_index', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'rw' => $this->input->post('rw',TRUE),
	    );

            $this->Rw_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('rw'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Rw_model->get_by_id($id);

        if ($row) {
            $data = array(
                'judul_page' => $this->judul_page,
                'konten' => 'rw/rw_form',
                'button' => 'Update',
                'action' => site_url('rw/update_action'),
		'id_rw' => set_value('id_rw', $row->id_rw),
		'rw' => set_value('rw', $row->rw),
	    );
            $this->load->view('v_index', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('rw'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_rw', TRUE));
        } else {
            $data = array(
		'rw' => $this->input->post('rw',TRUE),
	    );

            $this->Rw_model->update($this->input->post('id_rw', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('rw'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Rw_model->get_by_id($id);

        if ($row) {
            $this->Rw_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('rw'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('rw'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('rw', 'rw', 'trim|required');

	$this->form_validation->set_rules('id_rw', 'id_rw', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Rw.php */
/* Location: ./application/controllers/Rw.php */
/* Please DO NOT modify this information : */
/* Generated by Boy Kurniawan 2022-08-03 17:37:10 */
/* https://jualkoding.com */